import kotlin.String

/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Update this file with
 *   `$ ./gradlew buildSrcVersions`
 */
object Libs {
    /**
     * https://developer.android.com/jetpack/androidx
     */
    const val activity_ktx: String = "androidx.activity:activity-ktx:" + Versions.activity_ktx

    /**
     * https://developer.android.com/jetpack/androidx
     */
    const val appcompat: String = "androidx.appcompat:appcompat:" + Versions.appcompat

    /**
     * http://developer.android.com/tools/extras/support-library.html
     */
    const val browser: String = "androidx.browser:browser:" + Versions.browser

    /**
     * http://developer.android.com/tools/extras/support-library.html
     */
    const val collection_ktx: String = "androidx.collection:collection-ktx:" +
            Versions.collection_ktx

    /**
     * http://tools.android.com
     */
    const val constraintlayout: String = "androidx.constraintlayout:constraintlayout:" +
            Versions.constraintlayout

    /**
     * http://developer.android.com/tools/extras/support-library.html
     */
    const val core_ktx: String = "androidx.core:core-ktx:" + Versions.core_ktx

    /**
     * https://developer.android.com/jetpack/androidx
     */
    const val fragment: String = "androidx.fragment:fragment:" + Versions.fragment

    /**
     * https://developer.android.com/topic/libraries/architecture/index.html
     */
    const val lifecycle_compiler: String = "androidx.lifecycle:lifecycle-compiler:" +
            Versions.androidx_lifecycle

    /**
     * https://developer.android.com/topic/libraries/architecture/index.html
     */
    const val lifecycle_extensions: String = "androidx.lifecycle:lifecycle-extensions:" +
            Versions.androidx_lifecycle

    /**
     * https://developer.android.com/topic/libraries/architecture/index.html
     */
    const val navigation_fragment_ktx: String = "androidx.navigation:navigation-fragment-ktx:" +
            Versions.androidx_navigation

    /**
     * https://developer.android.com/topic/libraries/architecture/index.html
     */
    const val navigation_safe_args_gradle_plugin: String =
            "androidx.navigation:navigation-safe-args-gradle-plugin:" + Versions.androidx_navigation

    /**
     * https://developer.android.com/topic/libraries/architecture/index.html
     */
    const val navigation_ui_ktx: String = "androidx.navigation:navigation-ui-ktx:" +
            Versions.androidx_navigation

    /**
     * https://developer.android.com/testing
     */
    const val espresso_contrib: String = "androidx.test.espresso:espresso-contrib:" +
            Versions.androidx_test_espresso

    /**
     * https://developer.android.com/testing
     */
    const val espresso_core: String = "androidx.test.espresso:espresso-core:" +
            Versions.androidx_test_espresso

    /**
     * https://developer.android.com/testing
     */
    const val espresso_intents: String = "androidx.test.espresso:espresso-intents:" +
            Versions.androidx_test_espresso

    /**
     * https://developer.android.com/testing
     */
    const val espresso_web: String = "androidx.test.espresso:espresso-web:" +
            Versions.androidx_test_espresso

    /**
     * https://developer.android.com/testing
     */
    const val androidx_test_ext_junit: String = "androidx.test.ext:junit:" +
            Versions.androidx_test_ext_junit

    /**
     * https://developer.android.com/testing
     */
    const val androidx_test_ext_truth: String = "androidx.test.ext:truth:" +
            Versions.androidx_test_ext_truth

    /**
     * https://developer.android.com/testing
     */
    const val androidx_test_core: String = "androidx.test:core:" + Versions.androidx_test

    /**
     * https://developer.android.com/testing
     */
    const val androidx_test_rules: String = "androidx.test:rules:" + Versions.androidx_test

    /**
     * https://developer.android.com/testing
     */
    const val androidx_test_runner: String = "androidx.test:runner:" + Versions.androidx_test

    /**
     * https://github.com/akaita/easylauncher-gradle-plugin
     */
    const val easylauncher: String = "com.akaita.android:easylauncher:" + Versions.easylauncher

    /**
     * https://developer.android.com/studio
     */
    const val aapt2: String = "com.android.tools.build:aapt2:" + Versions.aapt2

    /**
     * https://developer.android.com/studio
     */
    const val com_android_tools_build_gradle: String = "com.android.tools.build:gradle:" +
            Versions.com_android_tools_build_gradle

    /**
     * https://developer.android.com/studio
     */
    const val lint_gradle: String = "com.android.tools.lint:lint-gradle:" + Versions.lint_gradle

    /**
     * https://github.com/shyiko/ktlint
     */
    const val ktlint: String = "com.github.shyiko:ktlint:" + Versions.ktlint

    /**
     * http://developer.android.com/tools/extras/support-library.html
     */
    const val material: String = "com.google.android.material:material:" + Versions.material

    /**
     * http://findbugs.sourceforge.net/
     */
    const val jsr305: String = "com.google.code.findbugs:jsr305:" + Versions.jsr305

    /**
     * http://github.com/google/truth
     */
    const val com_google_truth_truth: String = "com.google.truth:truth:" +
            Versions.com_google_truth_truth

    /**
     * https://github.com/JakeWharton/retrofit2-kotlinx-serialization-converter/
     */
    const val retrofit2_kotlinx_serialization_converter: String =
            "com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter:" +
            Versions.retrofit2_kotlinx_serialization_converter

    /**
     * https://github.com/JakeWharton/ThreeTenABP/
     */
    const val threetenabp: String = "com.jakewharton.threetenabp:threetenabp:" +
            Versions.threetenabp

    /**
     * https://github.com/JakeWharton/timber
     */
    const val timber: String = "com.jakewharton.timber:timber:" + Versions.timber

    /**
     * https://github.com/nhaarman/mockito-kotlin
     */
    const val mockito_kotlin_kt1_1: String = "com.nhaarman:mockito-kotlin-kt1.1:" +
            Versions.mockito_kotlin_kt1_1

    /**
     * http://github.com/square/leakcanary/
     */
    const val leakcanary_android_no_op: String =
            "com.squareup.leakcanary:leakcanary-android-no-op:" + Versions.com_squareup_leakcanary

    /**
     * http://github.com/square/leakcanary/
     */
    const val leakcanary_android: String = "com.squareup.leakcanary:leakcanary-android:" +
            Versions.com_squareup_leakcanary

    /**
     * https://github.com/square/okhttp
     */
    const val logging_interceptor: String = "com.squareup.okhttp3:logging-interceptor:" +
            Versions.com_squareup_okhttp3

    /**
     * https://github.com/square/okhttp
     */
    const val okhttp: String = "com.squareup.okhttp3:okhttp:" + Versions.com_squareup_okhttp3

    /**
     * https://github.com/square/retrofit/
     */
    const val retrofit: String = "com.squareup.retrofit2:retrofit:" + Versions.retrofit

    /**
     * https://github.com/tailoredmedia/AndroidAppUtil
     */
    const val util_async: String = "com.tailoredapps.androidutil:util-async:" +
            Versions.com_tailoredapps_androidutil

    /**
     * https://github.com/tailoredmedia/AndroidAppUtil
     */
    const val util_network: String = "com.tailoredapps.androidutil:util-network:" +
            Versions.com_tailoredapps_androidutil

    /**
     * https://github.com/tailoredmedia/AndroidAppUtil
     */
    const val util_optional: String = "com.tailoredapps.androidutil:util-optional:" +
            Versions.com_tailoredapps_androidutil

    /**
     * https://github.com/tailoredmedia/AndroidAppUtil
     */
    const val util_permissions: String = "com.tailoredapps.androidutil:util-permissions:" +
            Versions.com_tailoredapps_androidutil

    /**
     * https://github.com/tailoredmedia/AndroidAppUtil
     */
    const val util_ui: String = "com.tailoredapps.androidutil:util-ui:" +
            Versions.com_tailoredapps_androidutil

    /**
     * https://github.com/tailoredmedia/AndroidAppUtil
     */
    const val util_viewstate: String = "com.tailoredapps.androidutil:util-viewstate:" +
            Versions.com_tailoredapps_androidutil

    /**
     * http://github.com/vanniktech/gradle-dependency-graph-generator-plugin/
     */
    const val gradle_dependency_graph_generator_plugin: String =
            "com.vanniktech:gradle-dependency-graph-generator-plugin:" +
            Versions.gradle_dependency_graph_generator_plugin

    const val buildsrcversions: String = "de.fayard:buildSrcVersions:" + Versions.buildsrcversions

    /**
     * https://github.com/nidi3/graphviz-java
     */
    const val graphviz_java: String = "guru.nidi:graphviz-java:" + Versions.graphviz_java

    /**
     * https://github.com/coil-kt/coil
     */
    const val coil: String = "io.coil-kt:coil:" + Versions.coil

    /**
     * http://mockk.io
     */
    const val mockk: String = "io.mockk:mockk:" + Versions.mockk

    /**
     * http://junit.org
     */
    const val junit_junit: String = "junit:junit:" + Versions.junit_junit

    const val kluent: String = "org.amshove.kluent:kluent:" + Versions.kluent

    /**
     * https://kotlinlang.org/
     */
    const val kotlin_android_extensions_runtime: String =
            "org.jetbrains.kotlin:kotlin-android-extensions-runtime:" +
            Versions.org_jetbrains_kotlin

    /**
     * https://kotlinlang.org/
     */
    const val kotlin_android_extensions: String =
            "org.jetbrains.kotlin:kotlin-android-extensions:" + Versions.org_jetbrains_kotlin

    /**
     * https://kotlinlang.org/
     */
    const val kotlin_annotation_processing_gradle: String =
            "org.jetbrains.kotlin:kotlin-annotation-processing-gradle:" +
            Versions.org_jetbrains_kotlin

    /**
     * https://kotlinlang.org/
     */
    const val kotlin_gradle_plugin: String = "org.jetbrains.kotlin:kotlin-gradle-plugin:" +
            Versions.org_jetbrains_kotlin

    /**
     * https://kotlinlang.org/
     */
    const val kotlin_reflect: String = "org.jetbrains.kotlin:kotlin-reflect:" +
            Versions.org_jetbrains_kotlin

    /**
     * https://kotlinlang.org/
     */
    const val kotlin_scripting_compiler_embeddable: String =
            "org.jetbrains.kotlin:kotlin-scripting-compiler-embeddable:" +
            Versions.org_jetbrains_kotlin

    /**
     * https://kotlinlang.org/
     */
    const val kotlin_serialization_unshaded: String =
            "org.jetbrains.kotlin:kotlin-serialization-unshaded:" + Versions.org_jetbrains_kotlin

    /**
     * https://kotlinlang.org/
     */
    const val kotlin_serialization: String = "org.jetbrains.kotlin:kotlin-serialization:" +
            Versions.org_jetbrains_kotlin

    /**
     * https://kotlinlang.org/
     */
    const val kotlin_stdlib_jdk7: String = "org.jetbrains.kotlin:kotlin-stdlib-jdk7:" +
            Versions.org_jetbrains_kotlin

    /**
     * https://github.com/Kotlin/kotlinx.coroutines
     */
    const val kotlinx_coroutines_android: String =
            "org.jetbrains.kotlinx:kotlinx-coroutines-android:" +
            Versions.kotlinx_coroutines_android

    /**
     * https://github.com/Kotlin/kotlinx.coroutines
     */
    const val kotlinx_coroutines_core: String = "org.jetbrains.kotlinx:kotlinx-coroutines-core:" +
            Versions.kotlinx_coroutines_core

    /**
     * https://github.com/Kotlin/kotlinx.serialization
     */
    const val kotlinx_serialization_runtime: String =
            "org.jetbrains.kotlinx:kotlinx-serialization-runtime:" +
            Versions.kotlinx_serialization_runtime

    const val koin_android: String = "org.koin:koin-android:" + Versions.org_koin

    const val koin_androidx_scope: String = "org.koin:koin-androidx-scope:" + Versions.org_koin

    const val koin_androidx_viewmodel: String = "org.koin:koin-androidx-viewmodel:" +
            Versions.org_koin

    const val koin_core: String = "org.koin:koin-core:" + Versions.org_koin

    const val koin_test: String = "org.koin:koin-test:" + Versions.org_koin

    /**
     * https://github.com/mockito/mockito
     */
    const val mockito_android: String = "org.mockito:mockito-android:" + Versions.org_mockito

    /**
     * https://github.com/mockito/mockito
     */
    const val mockito_core: String = "org.mockito:mockito-core:" + Versions.org_mockito

    /**
     * http://www.powermock.org
     */
    const val powermock_api_mockito2: String = "org.powermock:powermock-api-mockito2:" +
            Versions.org_powermock

    /**
     * http://www.powermock.org
     */
    const val powermock_module_junit4_rule: String = "org.powermock:powermock-module-junit4-rule:" +
            Versions.org_powermock

    /**
     * http://www.powermock.org
     */
    const val powermock_module_junit4: String = "org.powermock:powermock-module-junit4:" +
            Versions.org_powermock
}
