import kotlin.String

/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Find which updates are available by running
 *     `$ ./gradlew buildSrcVersions`
 * This will only update the comments.
 *
 * YOU are responsible for updating manually the dependency version.
 */
object Versions {
    const val org_jetbrains_kotlinx_kotlinx_serialization: String = "0.13.0"

    const val org_jetbrains_kotlinx_kotlinx_coroutines: String = "1.3.2"

    const val io_github_reactivecircus_flowbinding: String = "0.5.0"

    const val com_squareup_leakcanary: String = "1.6.3"

    const val androidx_test_espresso: String = "3.2.0"

    const val org_jetbrains_kotlin: String = "1.3.50"

    const val androidx_room: String = "2.2.1"

    const val androidx_test: String = "1.2.0"

    const val org_koin: String = "2.0.1"

    const val io_ktor: String = "1.2.5"

    const val com_android_tools_build_gradle: String = "3.5.1"

    const val androidx_test_ext_junit: String = "1.1.1"

    const val io_fabric_tools_gradle: String = "1.31.2"

    const val junit_junit: String = "4.12"

    const val de_fayard_refreshversions_gradle_plugin: String = "0.7.0" // available: "0.8.1"

    const val lifecycle_viewmodel_ktx: String = "2.2.0-alpha04"

    const val firebase_dynamic_links: String = "19.0.0"

    const val lifecycle_livedata_ktx: String = "2.2.0-alpha04"

    const val lifecycle_runtime_ktx: String = "2.2.0-alpha04"

    const val lifecycle_extensions: String = "2.1.0"

    const val firebase_analytics: String = "17.2.1"

    const val lifecycle_compiler: String = "2.1.0"

    const val constraintlayout: String = "2.0.0-beta3"

    const val flow_extensions: String = "0.0.3"

    const val google_services: String = "4.3.2"

    const val collection_ktx: String = "1.1.0"

    const val ktlint_gradle: String = "9.0.0" // available: "9.1.0"

    const val activity_ktx: String = "1.1.0-rc01"

    const val control_core: String = "0.0.16"

    const val easylauncher: String = "1.3.1"

    const val fragment_ktx: String = "1.2.0-rc01"

    const val insetter_ktx: String = "0.1.1"

    const val crashlytics: String = "2.10.1"

    const val lint_gradle: String = "26.5.1"

    const val appcompat: String = "1.1.0"

    const val exoplayer: String = "2.10.6"

    const val core_ktx: String = "1.2.0-beta01"

    const val lce_data: String = "1.0.2"

    const val material: String = "1.2.0-alpha01"

    const val browser: String = "1.0.0"

    const val shimmer: String = "0.5.0"

    const val util_ui: String = "16"

    const val ktlint: String = "0.34.2" // available: "0.35.0"

    const val timber: String = "4.7.1"

    const val aapt2: String = "3.5.1-5435860"

    const val mockk: String = "1.9.3"

    const val truth: String = "1.2.0"

    const val coil: String = "0.8.0"

    /**
     * Current version: "5.6.3"
     * See issue 19: How to update Gradle itself?
     * https://github.com/jmfayard/buildSrcVersions/issues/19
     */
    const val gradleLatestVersion: String = "5.6.4"
}
